In [2]:
import numpy as np

In [3]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
temp = np.random.randint(0, 100, 20)
idx = temp
idx

array([51,  3, 17, 11, 86, 65, 52, 31, 93, 59, 48, 11, 32,  5, 30, 26, 24,
       93, 58, 14])

In [5]:
arr[idx]

array([51,  3, 17, 11, 86, 65, 52, 31, 93, 59, 48, 11, 32,  5, 30, 26, 24,
       93, 58, 14])

In [6]:
l = [1, 2, 5, 6, 34, 63]
arr[l]

array([ 1,  2,  5,  6, 34, 63])

In [12]:
arr = np.arange(20)
min = 5
max = 15
np.size(np.where(np.logical_and(arr > min, arr < max)))

9

In [14]:
string = "seasdfbji"
string[3:-1]

'sdfbj'

In [1]:
import numpy as np
arr = np.array([1,2,2,3,4])
arr = np.unique(arr)
arr

array([1, 2, 3, 4])