In [12]:
import torch
data = torch.randint(0, 10, [16, 5])
id, counts = torch.unique(data, return_counts=True, sorted=True)
id, counts

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 5,  6, 10,  6,  6, 10,  6, 14,  9,  8]))

In [5]:
data.shape

torch.Size([2, 3])

In [7]:
torch.cuda.is_available()

True

In [13]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [22]:
a = torch.tensor([[2, 3, 4], [5, 6, 7]])
b = torch.tensor([[[1, 2, 3], [4 ,5, 6], [7, 8, 9]], [[0, 1, 2], [1, 2, 3], [2, 3, 4]]])
c = torch.tensor([[[2, 3, 4], [2, 3, 4], [2, 3, 4]], [[5, 6, 7], [5, 6, 7], [5, 6, 7]]])
print(a)
print(b)
print(a.unsqueeze(1))
print(b * a.unsqueeze(1))
print(b * c)

tensor([[2, 3, 4],
        [5, 6, 7]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4]]])
tensor([[[2, 3, 4]],

        [[5, 6, 7]]])
tensor([[[ 2,  6, 12],
         [ 8, 15, 24],
         [14, 24, 36]],

        [[ 0,  6, 14],
         [ 5, 12, 21],
         [10, 18, 28]]])
tensor([[[ 2,  6, 12],
         [ 8, 15, 24],
         [14, 24, 36]],

        [[ 0,  6, 14],
         [ 5, 12, 21],
         [10, 18, 28]]])
