### 数据类型

In [1]:
import torch

In [2]:
a = torch.randn(2, 3)
a

tensor([[ 0.2649, -0.4609,  0.4746],
        [-0.7517, -1.3274,  1.0002]])

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a, torch.FloatTensor)

True

In [6]:
a = a.cuda()
isinstance(a, torch.cuda.FloatTensor)

True

In [7]:
a = a.cpu()
isinstance(a, torch.FloatTensor)

True

In [8]:
torch.tensor(1.)

tensor(1.)

In [9]:
a = torch.tensor(2.2)
a.shape

torch.Size([])

In [10]:
len(a.shape)

0

In [11]:
a.size()

torch.Size([])

In [12]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

```torch.Tensor([2, 3, 5])```

dimension = 3

size/shape = [2, 3, 5]

Tensor = [[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]]

In [13]:
torch.FloatTensor(2)

tensor([1.8341e+00, 4.5916e-41])

In [14]:
import numpy as np

In [15]:
data = np.ones(2)
data

array([1., 1.])

In [16]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [17]:
a = torch.ones(2)
a.shape

torch.Size([2])

In [18]:
a = torch.randn(2, 3)
a

tensor([[ 0.3322, -0.4910, -1.5604],
        [ 1.4022, -0.7877,  0.4857]])

In [19]:
a.shape

torch.Size([2, 3])

In [20]:
a.size()

torch.Size([2, 3])

In [21]:
a.size(0)

2

In [22]:
a.shape[1]

3

In [23]:
# 随机正态分布
a = torch.randn(1, 2, 3, 4)
a

tensor([[[[ 0.3328,  0.0419,  0.2618,  2.2002],
          [-1.6293, -0.8459,  1.3251, -1.3411],
          [ 1.1864,  0.3088,  0.6189,  0.9306]],

         [[-1.3955,  0.3444,  0.1778, -0.3457],
          [ 0.3628, -0.3500, -0.3987,  1.0161],
          [ 0.4471,  0.0802, -0.7109, -0.4962]]]])

In [24]:
b = a.transpose(1, 2)
b

tensor([[[[ 0.3328,  0.0419,  0.2618,  2.2002],
          [-1.3955,  0.3444,  0.1778, -0.3457]],

         [[-1.6293, -0.8459,  1.3251, -1.3411],
          [ 0.3628, -0.3500, -0.3987,  1.0161]],

         [[ 1.1864,  0.3088,  0.6189,  0.9306],
          [ 0.4471,  0.0802, -0.7109, -0.4962]]]])

In [25]:
c = a.view(1, 3, 2, 4)
c

tensor([[[[ 0.3328,  0.0419,  0.2618,  2.2002],
          [-1.6293, -0.8459,  1.3251, -1.3411]],

         [[ 1.1864,  0.3088,  0.6189,  0.9306],
          [-1.3955,  0.3444,  0.1778, -0.3457]],

         [[ 0.3628, -0.3500, -0.3987,  1.0161],
          [ 0.4471,  0.0802, -0.7109, -0.4962]]]])

In [26]:
d = a.reshape(1, 3, 2, 4)
d

tensor([[[[ 0.3328,  0.0419,  0.2618,  2.2002],
          [-1.6293, -0.8459,  1.3251, -1.3411]],

         [[ 1.1864,  0.3088,  0.6189,  0.9306],
          [-1.3955,  0.3444,  0.1778, -0.3457]],

         [[ 0.3628, -0.3500, -0.3987,  1.0161],
          [ 0.4471,  0.0802, -0.7109, -0.4962]]]])

RNN: torch.size(word, sentences, one-hot feature)

CNN: torch.size(batch_size, channels, height, weight)

In [27]:
a.numel()

24

In [28]:
a.dim()

4

### 创建Tensor

In [29]:
a = np.array([2, 3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [30]:
torch.tensor([2., 3.2])  # 推荐这么写

tensor([2.0000, 3.2000])

In [31]:
torch.Tensor([2, 3.2])  # 不要这么写

tensor([2.0000, 3.2000])

In [32]:
torch.Tensor(2, 3)  # 推荐这么写

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
torch.empty([2, 3])

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.3694e-38]])

In [34]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [35]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

In [36]:
a = torch.rand([2, 2])  # 均匀分布(0, 1)
# a = torch.rand(2, 2)
a 

tensor([[0.3012, 0.3029],
        [0.3222, 0.7111]])

In [37]:
torch.rand_like(a)  # 输入Tensor，并按这个Tensor的size来随机初始化一个Tensor

tensor([[0.1868, 0.5760],
        [0.8149, 0.7118]])

In [38]:
torch.randint(0, 10, [3, 3])

tensor([[6, 0, 7],
        [7, 9, 1],
        [0, 3, 9]])

In [39]:
torch.randn([3, 3])  # 正态分布N(0, 1)

tensor([[ 1.6111, -0.1406, -1.4233],
        [ 0.6319,  0.1145,  0.4533],
        [-0.1495, -1.0266,  0.3347]])

In [40]:
torch.normal(torch.full([10], 0.), torch.arange(1, 0, -0.1))  # torch.full的第二个参数必须是float类型

tensor([-1.2374,  0.8540,  1.0341, -0.7871, -0.8302, -0.0452,  0.1221,  0.2103,
         0.2292,  0.0911])

In [41]:
a.type()

'torch.DoubleTensor'

In [42]:
type(a)

torch.Tensor

In [43]:
isinstance(a, torch.FloatTensor)

False

In [44]:
a = a.cuda()
isinstance(a, torch.cuda.FloatTensor)

False

In [45]:
a = a.cpu()
isinstance(a, torch.FloatTensor)

False

In [46]:
torch.tensor(1.)

tensor(1.)

In [47]:
a = torch.tensor(2.2)
a.shape

torch.Size([])

In [48]:
len(a.shape)

0

In [49]:
a.size()

torch.Size([])

In [50]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

```torch.Tensor([2, 3, 5])```

dimension = 3

size/shape = [2, 3, 5]

Tensor = [[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]]

In [51]:
torch.FloatTensor(2)

tensor([1.4013e-45, 0.0000e+00], dtype=torch.float32)

In [52]:
import numpy as np

In [53]:
data = np.ones(2)
data

array([1., 1.])

In [54]:
torch.from_numpy(data)

tensor([1., 1.])

In [55]:
a = torch.ones(2)
a.shape

torch.Size([2])

In [56]:
a = torch.randn(2, 3)
a

tensor([[-0.2955,  0.9300, -0.8396],
        [-0.3207,  0.5181, -0.1392]])

In [57]:
a.shape

torch.Size([2, 3])

In [58]:
a.size()

torch.Size([2, 3])

In [59]:
a.size(0)

2

In [60]:
a.shape[1]

3

In [61]:
# 随机正态分布
a = torch.randn(1, 2, 3, 4)
a

tensor([[[[-1.6361, -2.2197,  1.0808,  0.2509],
          [ 1.3889, -0.2162,  0.1759, -0.4912],
          [ 0.7194, -0.4395, -0.0485,  0.4457]],

         [[ 0.8558, -1.9917, -1.7544,  1.2420],
          [-0.0265,  1.0932, -0.1729,  0.7355],
          [-0.8863,  1.2514,  0.2518,  0.7667]]]])

In [62]:
b = a.transpose(1, 2)
b

tensor([[[[-1.6361, -2.2197,  1.0808,  0.2509],
          [ 0.8558, -1.9917, -1.7544,  1.2420]],

         [[ 1.3889, -0.2162,  0.1759, -0.4912],
          [-0.0265,  1.0932, -0.1729,  0.7355]],

         [[ 0.7194, -0.4395, -0.0485,  0.4457],
          [-0.8863,  1.2514,  0.2518,  0.7667]]]])

In [63]:
c = a.view(1, 3, 2, 4)
c

tensor([[[[-1.6361, -2.2197,  1.0808,  0.2509],
          [ 1.3889, -0.2162,  0.1759, -0.4912]],

         [[ 0.7194, -0.4395, -0.0485,  0.4457],
          [ 0.8558, -1.9917, -1.7544,  1.2420]],

         [[-0.0265,  1.0932, -0.1729,  0.7355],
          [-0.8863,  1.2514,  0.2518,  0.7667]]]])

In [64]:
d = a.reshape(1, 3, 2, 4)
d

tensor([[[[-1.6361, -2.2197,  1.0808,  0.2509],
          [ 1.3889, -0.2162,  0.1759, -0.4912]],

         [[ 0.7194, -0.4395, -0.0485,  0.4457],
          [ 0.8558, -1.9917, -1.7544,  1.2420]],

         [[-0.0265,  1.0932, -0.1729,  0.7355],
          [-0.8863,  1.2514,  0.2518,  0.7667]]]])

RNN: torch.size(word, sentences, one-hot feature)

CNN: torch.size(batch_size, channels, height, weight)

In [65]:
a.numel()

24

In [66]:
a.dim()

4

### 创建Tensor

In [67]:
a = np.array([2, 3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000])

In [68]:
torch.tensor([2., 3.2])  # 推荐这么写

tensor([2.0000, 3.2000])

In [69]:
torch.Tensor([2, 3.2])  # 不要这么写

tensor([2.0000, 3.2000])

In [70]:
torch.Tensor(2, 3)  # 推荐这么写

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [71]:
torch.empty([2, 3])

tensor([[1.7802e-306, 6.2306e-307, 9.7911e-307],
        [6.8981e-307, 7.5659e-307, 6.2306e-307]])

In [72]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

In [73]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

In [74]:
a = torch.rand([2, 2])  # 均匀分布(0, 1)
# a = torch.rand(2, 2)
a 

tensor([[0.1739, 0.1522],
        [0.8953, 0.1338]])

In [75]:
torch.rand_like(a)  # 输入Tensor，并按这个Tensor的size来随机初始化一个Tensor

tensor([[0.7192, 0.6293],
        [0.6025, 0.8381]])

In [76]:
torch.randint(0, 10, [3, 3])

tensor([[1, 0, 7],
        [9, 4, 2],
        [0, 3, 0]])

In [77]:
torch.randn([3, 3])  # 正态分布N(0, 1)

tensor([[-1.5625, -0.2644, -1.0071],
        [-1.3384, -1.3473,  0.1133],
        [ 0.6684, -0.2545,  0.8798]])

In [78]:
# 打平数据
torch.normal(torch.full([10], 0.), torch.arange(1, 0, -0.1))

tensor([-0.0307, -1.3321,  0.1643,  0.8361,  0.3487,  0.1055, -0.1255, -0.0212,
        -0.0184,  0.0117])

In [79]:
torch.full([2, 3], 7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [80]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [81]:
torch.range(0, 10)  # 不推荐使用

C:\Users\liuhe\AppData\Local\Temp\ipykernel_20940\2983596431.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)  # 不推荐使用


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [82]:
torch.linspace(0, 10, 4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [83]:
torch.logspace(0, -1, 10)  # 10^(-1)=0.1, 10^0=1

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [84]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [85]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [86]:
torch.eye(3, 4)  # 只能接受一个或两个参数

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [87]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [88]:
a = torch.zeros(3, 3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [89]:
torch.randperm(10)  # random.shuffle

tensor([9, 0, 4, 3, 7, 6, 2, 1, 8, 5])

### 索引与切片

In [90]:
a = torch.rand(4, 3, 28, 28)
a[0].shape

torch.Size([3, 28, 28])

In [91]:
a[0, 0].shape

torch.Size([28, 28])

In [92]:
a[0, 0, 2, 4]

tensor(0.7180)

In [93]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [94]:
a[:2, :1, :, :].shape

torch.Size([2, 1, 28, 28])

In [95]:
a[:2, 1:, :, :].shape

torch.Size([2, 2, 28, 28])

In [96]:
a[:2, -1:, :, :].shape

torch.Size([2, 1, 28, 28])

In [97]:
a[:, :, 0:28:2, 0:28:2].shape  # 开始索引:结束索引:步长，任意位置可为空

torch.Size([4, 3, 14, 14])

In [98]:
a[:, :, ::2, ::2].shape

torch.Size([4, 3, 14, 14])

In [99]:
a.index_select(0, torch.tensor([0, 2])).shape

torch.Size([2, 3, 28, 28])

In [100]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [101]:
a[...].shape  # 任意所有维度

torch.Size([4, 3, 28, 28])

In [102]:
a[0, ...].shape

torch.Size([3, 28, 28])

In [103]:
a[:, 1, ...].shape

torch.Size([4, 28, 28])

In [104]:
a[..., :2].shape

torch.Size([4, 3, 28, 2])

In [105]:
x = torch.randn(3, 4)
x

tensor([[ 0.1585,  0.8929,  0.2708, -0.6558],
        [-0.0238,  0.0180, -0.7846, -1.8641],
        [-0.1607, -0.5171, -0.1463,  0.3098]])

In [106]:
mask = x.ge(0.5)  # greater than
mask

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [107]:
# 打平数据
torch.masked_select(x, mask)

tensor([0.8929])

In [108]:
torch.masked_select(x, mask).shape

torch.Size([1])

In [109]:
# 打平数据后选择
torch.take(x, torch.tensor([0, 2, 5]))

tensor([0.1585, 0.2708, 0.0180])

### 维度变换

In [110]:
a = torch.rand(4, 1, 28, 28)
a.shape

torch.Size([4, 1, 28, 28])

In [111]:
# view和reshape函数完全可以替换，推荐用reshape
a.view(4, 28 * 28)

tensor([[0.9285, 0.3299, 0.1798,  ..., 0.4040, 0.9431, 0.6218],
        [0.0069, 0.9438, 0.7204,  ..., 0.2133, 0.8902, 0.2241],
        [0.5717, 0.2261, 0.8432,  ..., 0.1031, 0.9046, 0.6993],
        [0.9497, 0.3263, 0.9743,  ..., 0.5182, 0.3853, 0.9551]])

In [112]:
a.view(4, 28 * 28).shape

torch.Size([4, 784])

In [113]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [114]:
b = a.unsqueeze(0).unsqueeze(0)
b.shape

torch.Size([1, 1, 4, 1, 28, 28])

In [115]:
b.squeeze(2).shape

torch.Size([1, 1, 4, 1, 28, 28])

In [116]:
b.squeeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [117]:
b.squeeze().shape

torch.Size([4, 28, 28])

squeeze/unsqueeze：增加或减少dim

expand/repeat：增加某一dim的size

expand：broadcasting，推荐使用，只改变了理解方式，不会主动复制数据，只会在需要的时候复制数据

repeat：memory copied，实实在在在内存中增加数据

两者在最终效果上等价

In [118]:
a = torch.rand(4, 32, 14, 14)
a.shape

torch.Size([4, 32, 14, 14])

In [119]:
b = torch.rand(1, 32, 1, 1)
b.shape

torch.Size([1, 32, 1, 1])

In [120]:
# 1->N是可以扩张的，M->N是不可扩张的
b.expand(4, 32, 14, 14).shape

torch.Size([4, 32, 14, 14])

In [121]:
b = torch.rand(1, 32, 1, 1)
b.shape

torch.Size([1, 32, 1, 1])

In [122]:
b.repeat(4, 32, 1, 1).shape

torch.Size([4, 1024, 1, 1])

In [123]:
b.repeat(4, 1, 1, 1).shape

torch.Size([4, 32, 1, 1])

In [124]:
a = torch.randn(3, 4)
a

tensor([[-1.7700,  1.4209, -0.8298,  0.2202],
        [-0.7291, -0.3162, -0.6792, -1.4573],
        [-1.0698, -0.3649,  1.1940,  0.7697]])

In [125]:
a.t()  # 只适用于矩阵

tensor([[-1.7700, -0.7291, -1.0698],
        [ 1.4209, -0.3162, -0.3649],
        [-0.8298, -0.6792,  1.1940],
        [ 0.2202, -1.4573,  0.7697]])

In [126]:
a = torch.randn(4, 3, 32, 32)
a.transpose(1, 3).shape

torch.Size([4, 32, 32, 3])

In [127]:
# a != b
# view操作会把维度信息丢失：[b, w, h, c]->[b, c, w, h]
# transpose函数会把Tensor变的不连续，需要contiguous函数将其拉直
b = a.transpose(1, 3).contiguous().view(4, 3 * 32 * 32).view(4, 3, 32, 32)
b.shape

torch.Size([4, 3, 32, 32])

In [128]:
# a == c
c= a.transpose(1, 3).contiguous().view(4, 3 * 32 * 32).view(4, 32, 32, 3).transpose(1, 3)
c.shape

torch.Size([4, 3, 32, 32])

In [129]:
torch.all(torch.eq(a, b))

tensor(False)

In [130]:
torch.all(torch.eq(a, c))

tensor(True)

In [131]:
b = torch.rand(4, 3, 28, 32)
b.permute(0, 2, 3, 1).shape

torch.Size([4, 28, 32, 3])

### Broadcast

1. insert 1 dim ahead
2. expand dims with size 1 to the same size
3. Feature maps: [4, 32, 14, 14]
4. Bias: [32, 1, 1]->[1, 32, 1, 1]->[4, 32, 14, 14]

In [132]:
a = torch.tensor([0, 10, 20, 30])  # size = [1, 4]
b = torch.tensor([[0], [1], [2]])  # size = [3, 1]
a + b

tensor([[ 0, 10, 20, 30],
        [ 1, 11, 21, 31],
        [ 2, 12, 22, 32]])

#### why bradcasting?

1.for actual demanding:

[class, students, scores]

add bias for every students: +5 scores

[4, 32, 8] + [4, 32, 8] => [4, 32, 8] + 5

2.memory consumption:

[4, 32, 8] => 1024

5 => 1

#### is it broadcasting-able?

match from last dim
1. if current dim.size = 1, expand to same
2. if either has no dim, insert one dim and expand to same
3. if dim_1.size = dim_2.size, pass
4. other wise, NOT bradcasting-able

cause: expand操作只能对dim.size=1的dim进行扩张，且若

In [133]:
a = torch.tensor([1, 2, 3, 4])
a + 3

tensor([4, 5, 6, 7])

In [134]:
a = torch.randn(1, 3, 32, 32)
b = torch.randn(4, 3, 1, 1)
(a + b).size()

torch.Size([4, 3, 32, 32])

### Merge and Split

In [135]:
a = torch.rand(4, 32, 8)
b = torch.rand(5, 32, 8)
torch.cat([a, b], dim=0).shape
# 非concat维度上的size必须一样

torch.Size([9, 32, 8])

In [136]:
a = torch.rand(4, 3, 16, 32)
b = torch.rand(4, 3, 16, 32)
torch.stack([a, b], dim=2).shape
# 插入了一个新的维度，两个tensor的各个维度的size必须一样

torch.Size([4, 3, 2, 16, 32])

In [137]:
a = torch.rand(32, 8)
b = torch.rand(32, 8)
torch.stack([a, b], 0).shape

torch.Size([2, 32, 8])

In [138]:
c = torch.stack([a, b], dim=0)
d, e = c.split([1, 1], dim = 0)
d.shape, e.shape
# by len

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [139]:
tensor_list = c.split(4, dim=1)
[tensor.shape for tensor in tensor_list]

[torch.Size([2, 4, 8]),
 torch.Size([2, 4, 8]),
 torch.Size([2, 4, 8]),
 torch.Size([2, 4, 8]),
 torch.Size([2, 4, 8]),
 torch.Size([2, 4, 8]),
 torch.Size([2, 4, 8]),
 torch.Size([2, 4, 8])]

In [140]:
d, e, f = c.split([16, 8, 8], dim=1)
d.shape, e.shape, f.shape

(torch.Size([2, 16, 8]), torch.Size([2, 8, 8]), torch.Size([2, 8, 8]))

In [141]:
d, e = c.chunk(2, dim=0)
d.shape, e.shape
# by size

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

### Math operation

In [142]:
# +, -, *, /
# add, sub, mul, div
# 完全一样，对应位置元素做运算

In [143]:
# 矩阵乘法
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.ones(2, 2)
torch.mm(a, b)  # 只适用于矩阵

tensor([[3., 3.],
        [7., 7.]])

In [144]:
torch.matmul(a, b)

tensor([[3., 3.],
        [7., 7.]])

In [145]:
a @ b

tensor([[3., 3.],
        [7., 7.]])

In [146]:
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)

In [147]:
torch.mm(a, b).shape

RuntimeError: self must be a matrix

In [148]:
torch.matmul(a, b).shape  # 只取最后两维做运算，前几维按照broadcast机制扩展

torch.Size([4, 3, 28, 32])

In [149]:
a = torch.full([2, 2], 3)
a.pow(2)  # 对应位置逐元素乘方、开方

tensor([[9, 9],
        [9, 9]])

In [150]:
a = a ** 2
a.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [151]:
a.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [152]:
a ** (0.5)  # 开方

tensor([[3., 3.],
        [3., 3.]])

In [153]:
a = torch.exp(torch.ones(2, 2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [154]:
torch.log(a)  # 默认以e为底，torch.log2()，torch.log10()

tensor([[1., 1.],
        [1., 1.]])

In [155]:
a = torch.tensor(3.14)
a.floor(), a.ceil(), a.trunc(), a.frac()  # 都是逐元素操作

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [156]:
a.round()  # 四舍五入

tensor(3.)

In [157]:
# 打印梯度的模：w.grad.norm(2)
grad = torch.rand(2, 3) * 15
grad.max()

tensor(10.2595)

In [158]:
grad.median()  # 中位数

tensor(5.5320)

In [159]:
grad.min()

tensor(3.8049)

In [160]:
grad.clamp(10)  # 把小于10的全变为10

tensor([[10.0000, 10.0000, 10.0000],
        [10.0000, 10.0000, 10.2595]])

In [161]:
grad.clamp(1, 10)  # 把小于1的全变为1，把大于10的全变为10

tensor([[ 3.8049,  6.7765,  8.7755],
        [ 5.5320,  5.4480, 10.0000]])

### 统计属性

In [164]:
# 范数
a = torch.full([8], 1.)
b = a.view(2, 4)
c = a.view(2, 2, 2)

In [165]:
a.norm(1), b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [166]:
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [167]:
b.norm(1, 1)

tensor([4., 4.])

In [168]:
b.norm(2, 1)

tensor([2., 2.])

In [169]:
c.norm(1, 0)

tensor([[2., 2.],
        [2., 2.]])

In [170]:
c.norm(2, 0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [174]:
a = torch.arange(8).view(2, 4).float()
# prod累乘
a.min(), a.max(), a.mean(), a.prod(), a.sum(), a.argmax(), a.argmin()

(tensor(0., dtype=torch.float32),
 tensor(7., dtype=torch.float32),
 tensor(3.5000, dtype=torch.float32),
 tensor(0., dtype=torch.float32),
 tensor(28., dtype=torch.float32),
 tensor(7),
 tensor(0))

In [175]:
# argmin/argmax会默认把tensor打平求索引
a = torch.randn(4, 10)
a[0]

tensor([-0.3231, -0.0072, -0.1087, -2.1980,  0.8411,  0.7130,  0.2512,  0.1334,
        -0.6985,  0.9850])

In [177]:
a.argmax(dim=1)

tensor([9, 7, 8, 4])

In [178]:
a.max(dim=1)  # 预测值/置信度

torch.return_types.max(
values=tensor([0.9850, 0.6840, 2.5456, 1.9905]),
indices=tensor([9, 7, 8, 4]))

In [179]:
a.max(dim=1, keepdim=True)  # 保持维度数量相同[4, 10]=>[4, 1]

torch.return_types.max(
values=tensor([[0.9850],
        [0.6840],
        [2.5456],
        [1.9905]]),
indices=tensor([[9],
        [7],
        [8],
        [4]]))

In [180]:
a.topk(3, dim=1)  # 比max提供更多的信息

torch.return_types.topk(
values=tensor([[0.9850, 0.8411, 0.7130],
        [0.6840, 0.5431, 0.4442],
        [2.5456, 2.0138, 1.2353],
        [1.9905, 1.6008, 0.4906]]),
indices=tensor([[9, 4, 5],
        [7, 0, 8],
        [8, 1, 7],
        [4, 3, 7]]))

In [181]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[-2.1980, -0.6985, -0.3231],
        [-2.4801, -1.9518, -0.9397],
        [-1.0659, -0.3825, -0.1500],
        [-0.9343, -0.8435, -0.5434]]),
indices=tensor([[3, 8, 0],
        [6, 3, 5],
        [2, 3, 9],
        [8, 9, 6]]))

In [182]:
a.kthvalue(8, dim=1)

torch.return_types.kthvalue(
values=tensor([0.7130, 0.4442, 1.2353, 0.4906]),
indices=tensor([5, 8, 7, 7]))

In [183]:
# compare: > >- < <= != ==
a > 0

tensor([[False, False, False, False,  True,  True,  True,  True, False,  True],
        [ True, False, False, False, False, False, False,  True,  True, False],
        [ True,  True, False, False, False,  True, False,  True,  True, False],
        [False,  True,  True,  True,  True, False, False,  True, False, False]])

In [184]:
torch.gt(a, 0)

tensor([[False, False, False, False,  True,  True,  True,  True, False,  True],
        [ True, False, False, False, False, False, False,  True,  True, False],
        [ True,  True, False, False, False,  True, False,  True,  True, False],
        [False,  True,  True,  True,  True, False, False,  True, False, False]])

In [185]:
a == 0

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [187]:
torch.eq(a, a)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [188]:
torch.equal(a, a)  # 比较完全一样

True

### 高价操作

In [191]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
a, b

(tensor([[ 2.3515,  0.6192, -0.1307],
         [-1.4406, -0.2063, -0.0183]]),
 tensor([[ 1.4337, -0.1971,  2.1572],
         [ 0.3937, -0.8039,  0.4288]]))

In [192]:
torch.where(torch.gt(a, b), a, b)

tensor([[ 2.3515,  0.6192,  2.1572],
        [ 0.3937, -0.2063,  0.4288]])

In [201]:
prob = torch.randn(4, 10)
idx = prob.topk(3, 1)
idx

torch.return_types.topk(
values=tensor([[1.1874, 1.1817, 1.0255],
        [1.6072, 1.4779, 0.9804],
        [0.9365, 0.7764, 0.5103],
        [1.1368, 1.0820, 0.9510]]),
indices=tensor([[8, 1, 7],
        [0, 2, 7],
        [4, 8, 6],
        [2, 4, 3]]))

In [202]:
idx = idx[1]
idx

tensor([[8, 1, 7],
        [0, 2, 7],
        [4, 8, 6],
        [2, 4, 3]])

In [203]:
label = torch.arange(10) + 100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [204]:
torch.gather(label.expand(4, 10), 1, idx.long())  # 查表

tensor([[108, 101, 107],
        [100, 102, 107],
        [104, 108, 106],
        [102, 104, 103]])